services:
db:
   image: postgres:16
   environment:
     POSTGRES_DB: ${cinema}
     POSTGRES_USER: ${postgres}
     POSTGRES_PASSWORD: ${Ghi2cgYmYgJVXNEkoCJWpKLfegbm1Xt7}
   ports:
     - "5432:5432"
   volumes:
     - postgres_data:/var/lib/postgresql/data
   
 
django-web:
   build: .
   container_name: rabiaadadi1510948/cinema-img
   ports:
     - "8000:8000"
   depends_on:
     - db
   
volumes:
   postgres_data: