# Generated by Django 4.2.7 on 2023-12-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='picture',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
