# Generated by Django 4.2.7 on 2023-12-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_film_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='picture',
            field=models.ImageField(upload_to='chemin/vers/dossier/upload/'),
        ),
    ]
